sudo: required
services:
  - docker
addons:
  apt:
    packages:
    - doxygen
    - doxygen-doc
    - doxygen-latex
    - doxygen-gui
    - graphviz
branches:
  only:
  - master
script:
  - cd .. && git clone https://github.com/alexbirne/Dockerfiles.git
  - cd DooFit && doxygen doxygen.conf
  - mv html ../Dockerfiles/deploy_doxygen
  - cp id_rsa_doofit.enc ../Dockerfiles/deploy_doxygen
  - cd ../Dockerfiles/deploy_doxygen
  - docker build --build-arg DECRYPTED_KEY=id_rsa_doofit.enc -t quick_doxygen_uploader .
  - docker run -e DEPLOY_HOST=$DEPLOY_HOST -e DEPLOY_USER=$DEPLOY_USER -e DEPLOY_PATH=$DEPLOY_PATH -e DECRYPTED_SSH_KEY=id_rsa_doofit.enc -e decrypted_key=$encrypted_2f2e4db5ecb3_key -e encrypted_iv=$encrypted_2f2e4db5ecb3_iv quick_doxygen_uploader:latest
notifications:
  email:
    recipients:
      - philipp.ibis@tu-dortmund.de
    on_success: change 
    on_failure: always 